version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Updating package lists..."
      - apt-get update
      - echo "Installing necessary tools..."
      - apt-get install -y dnsutils curl
      - echo "Installing Docker..."
      - apt-get install -y docker.io
      - echo "Installing Java Runtime Environment..."
      - apt-get install -y default-jre
      - pip install --upgrade awscli

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws sts get-caller-identity
      - echo "Checking DNS resolution..."
      - nslookup api.ecr-public.us-east-1.amazonaws.com
      - echo "Verifying endpoint connectivity..."
      - curl -v https://api.ecr-public.us-east-1.amazonaws.com/
      # Use the authentication token method
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
      - echo "Logged in to Amazon ECR"

  build:
    commands:
      - echo "Starting build phase"
      - echo "Building the Docker image..."
      - docker build -t k8-cicd-ecr-repo:latest .
      - docker tag k8-cicd-ecr-repo:latest 347209976305.dkr.ecr.ap-south-1.amazonaws.com/shubham:latest
      - docker push 347209976305.dkr.ecr.ap-south-1.amazonaws.com/shubham:latest
      - echo "Completed build phase"

  post_build:
    commands:
      - echo "Starting post-build phase"
      - echo "Pushing the Docker image to ECR..."
      - docker push public.ecr.aws/347209976305/k8-cicd-ecr-repo:latest
      - echo "Completed post-build phase"

artifacts:
  files:
    - '**/*'

