version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing necessary tools..."
      - apt-get update && apt-get install -y dnsutils curl
      - pip install --upgrade awscli

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws sts get-caller-identity
      - echo "Checking DNS resolution..."
      - nslookup api.ecr-public.us-east-1.amazonaws.com
      - echo "Verifying endpoint connectivity..."
      - curl -v https://api.ecr-public.us-east-1.amazonaws.com/

  build:
    commands:
      - echo "Starting build phase"
      - echo "Building the Docker image..."
      - docker build -t k8-cicd-ecr-repo:latest .
      - echo "Completed build phase"

  post_build:
    commands:
      - echo "Starting post-build phase"
      - echo "Tagging the Docker image..."
      - docker tag k8-cicd-ecr-repo:latest public.ecr.aws/h8p8y5w1/k8-cicd-ecr-repo:latest
      - echo "Pushing the Docker image to ECR..."
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
      - docker push public.ecr.aws/h8p8y5w1/k8-cicd-ecr-repo:latest
      - echo "Completed post-build phase"

artifacts:
  files:
    - '**/*'
